### ISSUE TITLE
Update Maps add-on documentation

### ISSUE THREAD

**Issue by sukhova** [jmix-framework/jmix-v1-v2-docs#672]
Describe Maps improvements 2.2:

- [x] [Support Clustering in maps #2575](https://github.com/jmix-framework/jmix/issues/2575)
- [x] [Zoom property type of GeoMapView and layers must be a double #2701](https://github.com/jmix-framework/jmix/issues/2701)
- [x] [Provide Move and Zoom events #2719](https://github.com/jmix-framework/jmix/issues/2719)
- [x] [Add zoomTo methods to Map #2735](https://github.com/jmix-framework/jmix/issues/2735)
- [x] [Support Heatmap layer in maps #2790](https://github.com/jmix-framework/jmix/issues/2790)
- [x] [Provide injecting Layer and Source from Map to View controller #2799](https://github.com/jmix-framework/jmix/issues/2799)
- [x] [Support MultiPoint, MultiPolygon, MultiLineString in Maps #2807](https://github.com/jmix-framework/jmix/issues/2807)
- [x] [Provide utility classes for creating feature styles #2824](https://github.com/jmix-framework/jmix/issues/2824)
