### ISSUE TITLE
Improve Data Repository documentation

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix-v1-v2-docs#679]
There are several things absent in Data Repositories documentation chapter:

- [x] `io.jmix.core.repository.ApplyConstraints` annotation usage (ability to use UnconstrainedDataManager)
- [x] `JmixDataRepositoryContext` parameter (see https://github.com/jmix-framework/jmix/issues/2490)
- [x]  Update [Features](https://docs.jmix.io/jmix/data-access/data-repositories.html#jmix-data-repository-features) part with newly added improvements: https://github.com/jmix-framework/jmix/issues/2523, https://github.com/jmix-framework/jmix/issues/2131
- [x] Clarify FetchPlan and Hints priority when different values set in method name/query and method parameters (see https://github.com/jmix-framework/jmix/issues/2490)

**Comment by sukhova** [comment]
Also describe how to create repositories in Studio. Information about this is available in **Support for Data Repositories** of **What's new** for 2.1
